app:
  mailer:
    # smtp, sandmail, test, file, mailcatcher, letter_opener
    service: smtp

    host: 'http://example.com'
    admin_email: 'admin@example.com'

    smtp:
      default:
        user_name: admin@example.com
        password:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        authentication: plain
        enable_starttls_auto: true

        address: 'smtp.yandex.ru'
        domain:  'yandex.ru'
        port:    25

      ecommerce:
        user_name: eshop@example.com
        password:  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

        authentication: plain
        enable_starttls_auto: true

        address: smtp.gmail.com
        domain:  gmail.com
        port:    587

    sandmail:
      location:  '/usr/sbin/sendmail'
      arguments: '-i -t'

    mailcatcher:
      address: 'localhost'
      port: 1025
