development:
  mysql41: 9156
  address: localhost

  min_infix_len: 3
  morphology: 'stem_en, stem_ru'

  indices_location:   /ABS/PATH/TO/Rails5App/db/SPHINX
  configuration_file: /ABS/PATH/TO/Rails5App/config/SPHINX.conf

  log:         /ABS/PATH/TO/Rails5App/log/searchd.log
  query_log:   /ABS/PATH/TO/Rails5App/log/searchd.query.log
  pid_file:    /ABS/PATH/TO/Rails5App/tmp/pids/searchd.pid
  binlog_path: /ABS/PATH/TO/Rails5App/tmp/binlog/production
